version: '3.8'

services:
  web:
    build: ./app
    command: gunicorn cf.wsgi:application --bind 0.0.0.0:8020
    volumes:
      - ./app/:/usr/src/app/
    ports:
      - 8020:8020
    env_file:
      - ./.env
    # network_mode: "host"        
    restart: unless-stopped
    depends_on:
      - db
  db:
    # network_mode: "host"        
    image: postgres:13.0-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      - POSTGRES_USER=kingship
      - POSTGRES_PASSWORD=kingship
      - POSTGRES_DB=dishchqdb1
    restart: always

volumes:
  postgres_data:


# version: '3.8'

# services:
#   web:
#     # network_mode: "host"
#     build: ./app
#     command: gunicorn cf.wsgi:application --bind 0.0.0.0:8020
#     volumes:
#       - ./app/:/usr/src/app/
#     ports:
#       - 8020:8020
#     # expose:
#     #   - 8020
#     env_file:
#       - ./.env
#     restart: unless-stopped
#     depends_on:
#       - db
#   db:
#     image: postgres:15
#     volumes:
#       - postgres_data:/var/lib/postgresql/data/
#     env_file:
#       - ./.env.db

# volumes:
#   postgres_data:
