# Generated by Django 4.2.4 on 2023-09-30 11:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_alter_profile_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='image',
            field=models.ImageField(blank=True, default='img/default-avatarpng.png', null=True, upload_to='profile_photos'),
        ),
    ]
