# Generated by Django 4.2.4 on 2023-08-17 18:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Ministry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('phone', models.CharField(blank=True, max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Owner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('phone', models.CharField(blank=True, max_length=255)),
                ('address', models.CharField(blank=True, max_length=255)),
                ('address1', models.CharField(blank=True, max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Returned',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Cheque',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_debited', models.DateField()),
                ('returned_other', models.CharField(blank=True, max_length=255, verbose_name='other')),
                ('chq_amount', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='cheque amount')),
                ('journal', models.CharField(blank=True, max_length=255)),
                ('cheque_date', models.DateField()),
                ('cheque_no', models.CharField(max_length=255, verbose_name='cheque number')),
                ('cheque_status', models.CharField(blank=True, choices=[('P', 'Paid'), ('U', 'Unpaid'), ('R', 'Returned')], default='U', max_length=1)),
                ('receipt_no', models.CharField(blank=True, max_length=255, verbose_name='receipt number')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('ministry', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cheques.ministry')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cheques', to='cheques.owner')),
                ('returned', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cheques.returned')),
            ],
            options={
                'ordering': ('date_debited',),
            },
        ),
    ]
