# Generated by Django 4.2.4 on 2023-08-15 19:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cheques', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Ministrty',
            new_name='Ministry',
        ),
    ]
