# Generated by Django 4.2.4 on 2023-08-19 14:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cheques', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='ministry',
            options={'ordering': ['-created_at'], 'verbose_name_plural': 'Ministries'},
        ),
        migrations.AlterModelOptions(
            name='returned',
            options={'verbose_name_plural': 'returns'},
        ),
    ]
