# Generated by Django 4.2.5 on 2023-10-31 21:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cheques', '0002_fee_cheque_fee'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cheque',
            name='cheque_status',
        ),
        migrations.CreateModel(
            name='ChequeStatusUpdate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('details', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('cheque', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='cheques_statuses', to='cheques.cheque')),
                ('cheque_status', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='statuses', to='cheques.chequestatus')),
            ],
        ),
    ]
