# Generated by Django 4.2.4 on 2023-08-15 19:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cheques', '0003_alter_ministry_email_alter_ministry_phone_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cheque',
            name='cheque_status',
            field=models.CharField(blank=True, choices=[('P', 'Paid'), ('R', 'Returned')], default='P', max_length=1),
        ),
        migrations.AlterField(
            model_name='cheque',
            name='returned_other',
            field=models.CharField(blank=True, max_length=255, verbose_name='other'),
        ),
    ]
