# Generated by Django 4.2.4 on 2023-08-16 15:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cheques', '0004_alter_cheque_cheque_status_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='cheque',
            options={'ordering': ('date_debited',)},
        ),
        migrations.RenameField(
            model_name='cheque',
            old_name='create_at',
            new_name='created_at',
        ),
        migrations.RenameField(
            model_name='cheque',
            old_name='update_at',
            new_name='updated_at',
        ),
    ]
