# Generated by Django 4.2.4 on 2023-09-06 13:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cheques', '0004_remove_cheque_returned_other'),
    ]

    operations = [
        migrations.AddField(
            model_name='cheque',
            name='is_deleted',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='cheque',
            name='ministry',
            field=models.ForeignKey(help_text="<small><a  class='text-muted' href='#'>add a new ministry</a></small>", on_delete=django.db.models.deletion.CASCADE, to='cheques.ministry'),
        ),
        migrations.AlterField(
            model_name='cheque',
            name='owner',
            field=models.ForeignKey(help_text="<small><a  class='text-muted' href='#'>add new owner</a></small>", on_delete=django.db.models.deletion.CASCADE, related_name='cheques', to='cheques.owner'),
        ),
        migrations.AlterField(
            model_name='cheque',
            name='returned',
            field=models.ForeignKey(help_text="<small><a  class='text-muted' href='#'>add a new reason for returning cheque</a></small>", on_delete=django.db.models.deletion.CASCADE, to='cheques.returned'),
        ),
    ]
