# Generated by Django 4.2.4 on 2023-08-16 17:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cheques', '0005_alter_cheque_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='owner',
            name='address',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='owner',
            name='address1',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='cheque',
            name='cheque_no',
            field=models.CharField(max_length=255, verbose_name='cheque number'),
        ),
        migrations.AlterField(
            model_name='cheque',
            name='cheque_status',
            field=models.CharField(blank=True, choices=[('P', 'Paid'), ('R', 'Returned')], default='R', max_length=1),
        ),
        migrations.AlterField(
            model_name='cheque',
            name='chq_amount',
            field=models.DecimalField(decimal_places=2, max_digits=10, verbose_name='cheque amount'),
        ),
        migrations.AlterField(
            model_name='cheque',
            name='receipt_no',
            field=models.CharField(max_length=255, verbose_name='receipt number'),
        ),
    ]
