# Generated by Django 4.2.4 on 2023-09-06 14:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cheques', '0005_cheque_is_deleted_alter_cheque_ministry_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cheque',
            name='ministry',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cheques.ministry'),
        ),
        migrations.AlterField(
            model_name='cheque',
            name='owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cheques', to='cheques.owner'),
        ),
        migrations.AlterField(
            model_name='cheque',
            name='returned',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cheques.returned'),
        ),
        migrations.AlterField(
            model_name='owner',
            name='name',
            field=models.CharField(max_length=255, unique=True),
        ),
    ]
