# Generated by Django 4.2.4 on 2023-08-16 17:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cheques', '0006_owner_address_owner_address1_alter_cheque_cheque_no_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cheque',
            name='owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cheques', to='cheques.owner'),
        ),
    ]
