# Generated by Django 4.2.4 on 2023-09-07 00:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cheques', '0006_alter_cheque_ministry_alter_cheque_owner_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='ministry',
            options={'ordering': ['name'], 'verbose_name_plural': 'Ministries'},
        ),
        migrations.AlterModelOptions(
            name='returned',
            options={'ordering': ('name',), 'verbose_name_plural': 'returns'},
        ),
        migrations.AlterField(
            model_name='cheque',
            name='returned',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='cheques.returned'),
        ),
    ]
