# Generated by Django 4.2.4 on 2023-08-16 18:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cheques', '0007_alter_cheque_owner'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='owner',
            options={'ordering': ['name']},
        ),
        migrations.AlterField(
            model_name='cheque',
            name='cheque_status',
            field=models.CharField(blank=True, choices=[('P', 'Paid'), ('U', 'Unpaid'), ('R', 'Returned')], default='U', max_length=1),
        ),
    ]
