# Generated by Django 4.2.4 on 2023-09-07 11:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cheques', '0007_alter_ministry_options_alter_returned_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ChequeStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.AddField(
            model_name='cheque',
            name='status',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='cheque_statuses', to='cheques.chequestatus'),
        ),
    ]
