# Generated by Django 4.2.4 on 2023-09-07 11:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cheques', '0008_chequestatus_cheque_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='chequestatus',
            name='desc',
            field=models.TextField(blank=True),
        ),
    ]
