# Generated by Django 4.2.4 on 2023-08-16 19:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cheques', '0008_alter_owner_options_alter_cheque_cheque_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='cheque',
            name='journnal',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='cheque',
            name='receipt_no',
            field=models.CharField(blank=True, max_length=255, verbose_name='receipt number'),
        ),
    ]
