# Generated by Django 4.2.4 on 2023-08-16 19:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cheques', '0009_cheque_journnal_alter_cheque_receipt_no'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cheque',
            old_name='journnal',
            new_name='journal',
        ),
    ]
