# Generated by Django 4.2.4 on 2023-09-07 11:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cheques', '0009_chequestatus_desc'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cheque',
            name='status',
            field=models.ForeignKey(blank=True, default=1, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='cheque_statuses', to='cheques.chequestatus'),
        ),
    ]
