# Generated by Django 4.2.4 on 2023-09-07 11:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cheques', '0010_alter_cheque_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cheque',
            name='cheque_status',
        ),
        migrations.RemoveField(
            model_name='cheque',
            name='status',
        ),
    ]
