# Generated by Django 4.2.4 on 2023-09-11 22:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cheques', '0012_cheque_cheque_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cheque',
            name='cheque_status',
        ),
    ]
