# Generated by Django 4.2.4 on 2023-09-28 21:34

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('cheques', '0014_cheque_cheque_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='ChequeComment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('cheque', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='comments', to='cheques.cheque')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='comment_created', to=settings.AUTH_USER_MODEL)),
                ('upated_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='comment_updated', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
