# Generated by Django 4.2.4 on 2023-09-28 21:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cheques', '0015_chequecomment'),
    ]

    operations = [
        migrations.AddField(
            model_name='cheque',
            name='cheque',
            field=models.FileField(blank=True, null=True, upload_to='cheques'),
        ),
    ]
