# Generated by Django 4.2.4 on 2023-09-30 02:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cheques', '0016_cheque_cheque'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='chequecomment',
            options={'ordering': ('-created_at',)},
        ),
    ]
